server:
  servlet:
    context-path: /hillside
  shutdown: graceful
spring:
  application:
    name: HillsideApplication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: hillside_master
    url: jdbc:mysql://127.0.0.1:3306/${spring.datasource.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  #    master:
  #      driver-class-name: com.mysql.cj.jdbc.Driver
  #      name: hillside_master
  #      url: jdbc:mysql://127.0.0.1:3306/${spring.datasource.master.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
  #      username: root
  #      password: root
  #    slave:
  #      driver-class-name: com.mysql.cj.jdbc.Driver
  #      name: hillside_slave
  #      url: jdbc:mysql://127.0.0.1:3306/${spring.datasource.slave.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
  #      username: root
  #      password: root
  jpa:
    open-in-view: false
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
#eureka:
#  instance:
#    hostname: localhost #指定主机地址
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/registration-center/eureka/
logging:
  level:
    root: info