server:
  port: 8082 #指定运行端口
  servlet:
    context-path: /gateway
spring:
  application:
    name: HillsideGatewayApplication #指定服务名称
eureka:
  instance:
    hostname: localhost #指定主机地址
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/registration-center/eureka/
logging:
  level:
    root: info
